//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Areas.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAIDANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAIDANG()
        {
            this.CT_BAIDANG = new HashSet<CT_BAIDANG>();
            this.CT_DONHANG = new HashSet<CT_DONHANG>();
        }
    
        public int MaBaiDang { get; set; }
        public int MaTaiKhoan { get; set; }
        public System.DateTime NgayDang { get; set; }
        public string TenSanPham { get; set; }
        public int DonGia { get; set; }
        public string MoTa { get; set; }
        public byte[] HinhAnh { get; set; }
        public int MaPhanLoai { get; set; }
        public string TrangThai { get; set; }
    
        public virtual PHANLOAI PHANLOAI { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BAIDANG> CT_BAIDANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_DONHANG> CT_DONHANG { get; set; }
    }
}
