//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Areas.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGTU
    {
        public string MaChungTu { get; set; }
        public int MaTaiKhoan { get; set; }
        public System.DateTime NgayLap { get; set; }
        public int TongTien { get; set; }
        public int SoBaiDang { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
