//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Areas.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BAIDANG
    {
        public int MaBaiDang { get; set; }
        public string MauSac { get; set; }
        public string KichThuoc { get; set; }
        public int MaCT { get; set; }
        public int SoLuong { get; set; }
    
        public virtual BAIDANG BAIDANG { get; set; }
    }
}
