//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EC.Areas.Client.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANGBAN
    {
        public int MaDonHangBan { get; set; }
        public int MaDonHangMua { get; set; }
        public int MaTaiKhoanBan { get; set; }
        public int MaTaiKhoanMua { get; set; }
        public int TongTien { get; set; }
        public int SoLuong { get; set; }
    
        public virtual DONHANGMUA DONHANGMUA { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        public virtual TAIKHOAN TAIKHOAN1 { get; set; }
    }
}
